{% set name = "waitress" %}
{% set version = "1.4.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 67a60a376f0eb335ed88967c42b73983a58d66a2a72eb9009a42725f7453b142

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . -vv"
  entry_points:
    - waitress-serve = waitress.runner:run

requirements:
  build:
    - python >=2.7
    - pip
  run:
    - python >=2.7

test:
  imports:
    - waitress
  commands:
    - waitress-serve --help

about:
  home: https://github.com/Pylons/waitress
  license: ZPL-2.0
  license_family: OTHER
  license_file: LICENSE.txt
  summary: 'Production-quality pure-Python WSGI server'
  description: |
    Waitress is meant to be a production-quality pure-Python WSGI server with
    very acceptable performance. It has no dependencies except ones which live
    in the Python standard library. It runs on CPython on Unix and Windows under
    Python 2.7+ and Python 3.3+. It is also known to run on PyPy 1.6.0+ on UNIX.
    It supports HTTP/1.0 and HTTP/1.1.
  doc_url: http://docs.pylonsproject.org/projects/waitress/en/latest/
  dev_url: https://github.com/Pylons/waitress

extra:
  recipe-maintainers:
    - carlodri
